"""Agregar columna fecha_hora a venta

Revision ID: 9c0ebf3aae04
Revises: 
Create Date: 2025-05-05 15:54:56.424501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0ebf3aae04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_insumo')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('fecha_hora')

    op.create_table('producto_insumo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('insumo_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
